### PR TITLE
feat: make oembed requests default to json type

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
No need to pass `format` if their's only one.

We can make it default to `json` whenever we would want to support `xml` format too

### CODE REVIEW

**Comment by smeijer** [comment]
Don't we need to throw a `501 NOT IMPLEMENTED` if the consumer asks for `format=xml`?

**Comment by MichaelDeBoey** [comment]
@smeijer Fixed 🙂

**Comment by smeijer** [comment]
Thanks :sunglasses: 

@all-contributors please add @MichaelDeBoey for code

**Comment by MichaelDeBoey** [comment]
It's a pleasure to help out! 🙂

**Pull request merged**
