### PR TITLE
feat: add responsive header

### LINKED ISSUE #31: The navbar should be made responsive
It doesn't look very nice at the moment:

image

### PR DESCRIPTION
**Pull request by marcosvega91**
fix #31 
What do you think?
header

### CODE REVIEW

**Comment by smeijer** [comment]
I love it! I was thinking about a dropout menu, but this is way better!

Maybe we can keep "Github" in the top bar, and move it to the right? That way we keep a bit separation between playground links, and testing-library links.

What do you think?

image

**Comment by marcosvega91** [comment]
Yes we can do. I was inspired by [docusaurus](https://docusaurus.io/)

**Comment by marcosvega91** [comment]
I have fixed. Now it is as the image below

image

**Comment by smeijer** [comment]
Nice! I'll first want to get #26 merged, it's almost there. This might need to get some conflicts resolved afterwards, but we'll see.

Thanks.

**Comment by smeijer** [comment]
Screenshot_20200528-214109

**Pull request merged**
