### PR TITLE
feat: use `getSuggestedQuery` from `@testing-library/dom`

### LINKED ISSUE #112: use the official testing-lib getSuggestedQuery for query advise
Now that `@testing-library/dom` has adopted the query suggestions, and added it to its core, we can use the exported `getSuggestedQuery` method to ensure that we are on the same page as the official lib.

```js
// getSuggestedQuery(...)
{
  queryName: 'Role',
  queryMethod: 'getByRole',
  queryArgs: ['button', { name: /submit/i }],
  variant: 'get',
  toString() // » getByRole('button', { name: /submit/i })
}
```

For this to work, we need to upgrade `@testing-library/dom` to `7.11.0` (or higher), to include the changes from https://github.com/testing-library/dom-testing-library/pull/608

### PR DESCRIPTION
**Pull request by marcosvega91**
closes #112

### CODE REVIEW

**Comment by smeijer** [comment]
@marcosvega91, is it just broken, or weren't you finished yet? :innocent:

**Comment by marcosvega91** [comment]
What is the problem?

**Comment by smeijer** [comment]
Selecting elements, now renders errors?

ezgif-2-0d0fed03a885

**Comment by marcosvega91** [comment]
fixed :)

**Pull request merged**
