### PR TITLE
chore: Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **5%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /public/android-chrome-512x512.png | 18.29kb | 11.16kb | 38.97% |
| /public/android-chrome-192x192.png | 4.51kb | 3.09kb | 31.45% |
| /public/apple-touch-icon.png | 4.32kb | 3.15kb | 27.00% |
| /docs/testing-playground-com.gif | 787.48kb | 757.41kb | 3.82% |
| | | | |
| **Total :** | **814.60kb** | **774.82kb** | **4.88%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in your full account).
It will automatically send PRs for image optimization 🙂

**Comment by MichaelDeBoey** [comment]
@smeijer Tests are failing, but I have no clue why tbh.

This is just an automatic minification of the images in a lossless format.

**Comment by smeijer** [comment]
Thanks :)

The test is just the `cache action` messing up again :disappointed:  (nothing to worry about)

image

**Comment by smeijer** [comment]
> If you want, you can install [imgbot.net](https://imgbot.net) in this repo (or in your full account).
> It will automatically send PRs for image optimization

Awesome, Done!

**Pull request merged**
