### PR TITLE
feat: render placeholder image when no markup is provided

### PR DESCRIPTION
**Pull request by delca85**
Following up [#30](https://github.com/smeijer/testing-playground/issues/30), I inserted an image when no html is inserted and a warning message if in absence of html and query.

### CODE REVIEW

**Comment by smeijer** [comment]
Thanks! It's looking great!

Except for smaller screens. Can you try fix the overflow issue?

image

**Comment by delca85** [comment]
Hi! I think I've checked that issue! Let me know if there is some additional work to do.

**Comment by smeijer** [comment]
I don't think the text is the issue. I think the image should scale.

**Comment by delca85** [comment]
I should fix the image resize issue.

**Comment by smeijer** [comment]
I've pushed one tiny change, to remove the changes to `package-lock.json`. I don't think those should be here. But besides that, it's looking awesome. So I'm going to merge it.

Thanks for putting your time into this.

**Comment by smeijer** [comment]
@all-contributors please add @delca85 for code

**Pull request merged**
